### ISSUE TITLE
Fluent org member request

### ISSUE THREAD

**Issue by adiforluls** [calyptia/fluent-bit-infra#185]
Hi @patrick-stephens @agup006 , following up on https://github.com/fluent/fluent-bit-infra/issues/184
I accepted the invite to become fluent-operator maintainer yesterday sometime after this thread was closed, I don't see myself listed as a fluent org member https://github.com/orgs/fluent/people

I'm definitely interested in becoming a member of fluent community, can you help here? Thanks in advance!

**Comment by patrick-stephens** [comment]
Weird, I invited you as a member but it was also the same time Github was having "issues" so may be related.

**Comment by adiforluls** [comment]
Np, thanks!
